apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rhobs-synthetics-api-rolebinding
  labels:
    app: rhobs-synthetics-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rhobs-synthetics-api-role
subjects:
- kind: ServiceAccount
  name: rhobs-synthetics-api
